export interface SurahMeta {
  number: number;
  name: string;
  englishName: string;
  indonesianName: string;
  ayahCount: number;
  type: 'Makkiyyah' | 'Madaniyyah';
  juz: number;
}

export const SURAH_LIST: SurahMeta[] = [
  { number: 1, name: 'الفاتحة', englishName: 'Al-Fatihah', indonesianName: 'Pembukaan', ayahCount: 7, type: 'Makkiyyah', juz: 1 },
  { number: 2, name: 'البقرة', englishName: 'Al-Baqarah', indonesianName: 'Sapi Betina', ayahCount: 286, type: 'Madaniyyah', juz: 1 },
  { number: 3, name: 'آل عمران', englishName: 'Ali Imran', indonesianName: 'Keluarga Imran', ayahCount: 200, type: 'Madaniyyah', juz: 3 },
  { number: 4, name: 'النساء', englishName: 'An-Nisa', indonesianName: 'Wanita', ayahCount: 176, type: 'Madaniyyah', juz: 4 },
  { number: 5, name: 'المائدة', englishName: 'Al-Maidah', indonesianName: 'Hidangan', ayahCount: 120, type: 'Madaniyyah', juz: 6 },
  { number: 6, name: 'الأنعام', englishName: 'Al-Anam', indonesianName: 'Binatang Ternak', ayahCount: 165, type: 'Makkiyyah', juz: 7 },
  { number: 7, name: 'الأعراف', englishName: 'Al-Araf', indonesianName: 'Tempat Tertinggi', ayahCount: 206, type: 'Makkiyyah', juz: 8 },
  { number: 8, name: 'الأنفال', englishName: 'Al-Anfal', indonesianName: 'Rampasan Perang', ayahCount: 75, type: 'Madaniyyah', juz: 9 },
  { number: 9, name: 'التوبة', englishName: 'At-Tawbah', indonesianName: 'Pengampunan', ayahCount: 129, type: 'Madaniyyah', juz: 10 },
  { number: 10, name: 'يونس', englishName: 'Yunus', indonesianName: 'Yunus', ayahCount: 109, type: 'Makkiyyah', juz: 11 },
  { number: 11, name: 'هود', englishName: 'Hud', indonesianName: 'Hud', ayahCount: 123, type: 'Makkiyyah', juz: 11 },
  { number: 12, name: 'يوسف', englishName: 'Yusuf', indonesianName: 'Yusuf', ayahCount: 111, type: 'Makkiyyah', juz: 12 },
  { number: 13, name: 'الرعد', englishName: 'Ar-Rad', indonesianName: 'Guruh', ayahCount: 43, type: 'Madaniyyah', juz: 13 },
  { number: 14, name: 'إبراهيم', englishName: 'Ibrahim', indonesianName: 'Ibrahim', ayahCount: 52, type: 'Makkiyyah', juz: 13 },
  { number: 15, name: 'الحجر', englishName: 'Al-Hijr', indonesianName: 'Al-Hijr', ayahCount: 99, type: 'Makkiyyah', juz: 14 },
  { number: 16, name: 'النحل', englishName: 'An-Nahl', indonesianName: 'Lebah', ayahCount: 128, type: 'Makkiyyah', juz: 14 },
  { number: 17, name: 'الإسراء', englishName: 'Al-Isra', indonesianName: 'Perjalanan Malam', ayahCount: 111, type: 'Makkiyyah', juz: 15 },
  { number: 18, name: 'الكهف', englishName: 'Al-Kahf', indonesianName: 'Gua', ayahCount: 110, type: 'Makkiyyah', juz: 15 },
  { number: 19, name: 'مريم', englishName: 'Maryam', indonesianName: 'Maryam', ayahCount: 98, type: 'Makkiyyah', juz: 16 },
  { number: 20, name: 'طه', englishName: 'Taha', indonesianName: 'Taha', ayahCount: 135, type: 'Makkiyyah', juz: 16 },
  { number: 21, name: 'الأنبياء', englishName: 'Al-Anbiya', indonesianName: 'Para Nabi', ayahCount: 112, type: 'Makkiyyah', juz: 17 },
  { number: 22, name: 'الحج', englishName: 'Al-Hajj', indonesianName: 'Haji', ayahCount: 78, type: 'Madaniyyah', juz: 17 },
  { number: 23, name: 'المؤمنون', englishName: 'Al-Muminun', indonesianName: 'Orang Beriman', ayahCount: 118, type: 'Makkiyyah', juz: 18 },
  { number: 24, name: 'النور', englishName: 'An-Nur', indonesianName: 'Cahaya', ayahCount: 64, type: 'Madaniyyah', juz: 18 },
  { number: 25, name: 'الفرقان', englishName: 'Al-Furqan', indonesianName: 'Pembeda', ayahCount: 77, type: 'Makkiyyah', juz: 18 },
  { number: 26, name: 'الشعراء', englishName: 'Asy-Syuara', indonesianName: 'Para Penyair', ayahCount: 227, type: 'Makkiyyah', juz: 19 },
  { number: 27, name: 'النمل', englishName: 'An-Naml', indonesianName: 'Semut', ayahCount: 93, type: 'Makkiyyah', juz: 19 },
  { number: 28, name: 'القصص', englishName: 'Al-Qasas', indonesianName: 'Cerita', ayahCount: 88, type: 'Makkiyyah', juz: 20 },
  { number: 29, name: 'العنكبوت', englishName: 'Al-Ankabut', indonesianName: 'Laba-laba', ayahCount: 69, type: 'Makkiyyah', juz: 20 },
  { number: 30, name: 'الروم', englishName: 'Ar-Rum', indonesianName: 'Bangsa Romawi', ayahCount: 60, type: 'Makkiyyah', juz: 21 },
  { number: 31, name: 'لقمان', englishName: 'Luqman', indonesianName: 'Luqman', ayahCount: 34, type: 'Makkiyyah', juz: 21 },
  { number: 32, name: 'السجدة', englishName: 'As-Sajdah', indonesianName: 'Sujud', ayahCount: 30, type: 'Makkiyyah', juz: 21 },
  { number: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', indonesianName: 'Golongan Bersekutu', ayahCount: 73, type: 'Madaniyyah', juz: 21 },
  { number: 34, name: 'سبأ', englishName: 'Saba', indonesianName: 'Saba', ayahCount: 54, type: 'Makkiyyah', juz: 22 },
  { number: 35, name: 'فاطر', englishName: 'Fatir', indonesianName: 'Pencipta', ayahCount: 45, type: 'Makkiyyah', juz: 22 },
  { number: 36, name: 'يس', englishName: 'Yasin', indonesianName: 'Yasin', ayahCount: 83, type: 'Makkiyyah', juz: 22 },
  { number: 37, name: 'الصافات', englishName: 'As-Saffat', indonesianName: 'Yang Berbaris', ayahCount: 182, type: 'Makkiyyah', juz: 23 },
  { number: 38, name: 'ص', englishName: 'Sad', indonesianName: 'Sad', ayahCount: 88, type: 'Makkiyyah', juz: 23 },
  { number: 39, name: 'الزمر', englishName: 'Az-Zumar', indonesianName: 'Rombongan', ayahCount: 75, type: 'Makkiyyah', juz: 23 },
  { number: 40, name: 'غافر', englishName: 'Ghafir', indonesianName: 'Yang Maha Pengampun', ayahCount: 85, type: 'Makkiyyah', juz: 24 },
  { number: 41, name: 'فصلت', englishName: 'Fussilat', indonesianName: 'Dijelaskan', ayahCount: 54, type: 'Makkiyyah', juz: 24 },
  { number: 42, name: 'الشورى', englishName: 'Asy-Syura', indonesianName: 'Musyawarah', ayahCount: 53, type: 'Makkiyyah', juz: 25 },
  { number: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', indonesianName: 'Perhiasan', ayahCount: 89, type: 'Makkiyyah', juz: 25 },
  { number: 44, name: 'الدخان', englishName: 'Ad-Dukhan', indonesianName: 'Kabut', ayahCount: 59, type: 'Makkiyyah', juz: 25 },
  { number: 45, name: 'الجاثية', englishName: 'Al-Jasiyah', indonesianName: 'Berlutut', ayahCount: 37, type: 'Makkiyyah', juz: 25 },
  { number: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', indonesianName: 'Bukit-bukit Pasir', ayahCount: 35, type: 'Makkiyyah', juz: 26 },
  { number: 47, name: 'محمد', englishName: 'Muhammad', indonesianName: 'Muhammad', ayahCount: 38, type: 'Madaniyyah', juz: 26 },
  { number: 48, name: 'الفتح', englishName: 'Al-Fath', indonesianName: 'Kemenangan', ayahCount: 29, type: 'Madaniyyah', juz: 26 },
  { number: 49, name: 'الحجرات', englishName: 'Al-Hujurat', indonesianName: 'Kamar-kamar', ayahCount: 18, type: 'Madaniyyah', juz: 26 },
  { number: 50, name: 'ق', englishName: 'Qaf', indonesianName: 'Qaf', ayahCount: 45, type: 'Makkiyyah', juz: 26 },
  { number: 51, name: 'الذاريات', englishName: 'Az-Zariyat', indonesianName: 'Angin yang Menerbangkan', ayahCount: 60, type: 'Makkiyyah', juz: 26 },
  { number: 52, name: 'الطور', englishName: 'At-Tur', indonesianName: 'Bukit', ayahCount: 49, type: 'Makkiyyah', juz: 27 },
  { number: 53, name: 'النجم', englishName: 'An-Najm', indonesianName: 'Bintang', ayahCount: 62, type: 'Makkiyyah', juz: 27 },
  { number: 54, name: 'القمر', englishName: 'Al-Qamar', indonesianName: 'Bulan', ayahCount: 55, type: 'Makkiyyah', juz: 27 },
  { number: 55, name: 'الرحمن', englishName: 'Ar-Rahman', indonesianName: 'Yang Maha Pemurah', ayahCount: 78, type: 'Madaniyyah', juz: 27 },
  { number: 56, name: 'الواقعة', englishName: 'Al-Waqiah', indonesianName: 'Hari Kiamat', ayahCount: 96, type: 'Makkiyyah', juz: 27 },
  { number: 57, name: 'الحديد', englishName: 'Al-Hadid', indonesianName: 'Besi', ayahCount: 29, type: 'Madaniyyah', juz: 27 },
  { number: 58, name: 'المجادلة', englishName: 'Al-Mujadilah', indonesianName: 'Wanita yang Mengajukan Gugatan', ayahCount: 22, type: 'Madaniyyah', juz: 28 },
  { number: 59, name: 'الحشر', englishName: 'Al-Hasyr', indonesianName: 'Pengusiran', ayahCount: 24, type: 'Madaniyyah', juz: 28 },
  { number: 60, name: 'الممتحنة', englishName: 'Al-Mumtahanah', indonesianName: 'Wanita yang Diuji', ayahCount: 13, type: 'Madaniyyah', juz: 28 },
  { number: 61, name: 'الصف', englishName: 'As-Saf', indonesianName: 'Barisan', ayahCount: 14, type: 'Madaniyyah', juz: 28 },
  { number: 62, name: 'الجمعة', englishName: 'Al-Jumuah', indonesianName: 'Hari Jumat', ayahCount: 11, type: 'Madaniyyah', juz: 28 },
  { number: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', indonesianName: 'Orang-orang Munafik', ayahCount: 11, type: 'Madaniyyah', juz: 28 },
  { number: 64, name: 'التغابن', englishName: 'At-Tagabun', indonesianName: 'Pengungkapan Kesalahan', ayahCount: 18, type: 'Madaniyyah', juz: 28 },
  { number: 65, name: 'الطلاق', englishName: 'At-Talaq', indonesianName: 'Talak', ayahCount: 12, type: 'Madaniyyah', juz: 28 },
  { number: 66, name: 'التحريم', englishName: 'At-Tahrim', indonesianName: 'Pengharaman', ayahCount: 12, type: 'Madaniyyah', juz: 28 },
  { number: 67, name: 'الملك', englishName: 'Al-Mulk', indonesianName: 'Kerajaan', ayahCount: 30, type: 'Makkiyyah', juz: 29 },
  { number: 68, name: 'القلم', englishName: 'Al-Qalam', indonesianName: 'Pena', ayahCount: 52, type: 'Makkiyyah', juz: 29 },
  { number: 69, name: 'الحاقة', englishName: 'Al-Haqqah', indonesianName: 'Hari Kiamat', ayahCount: 52, type: 'Makkiyyah', juz: 29 },
  { number: 70, name: 'المعارج', englishName: 'Al-Maarij', indonesianName: 'Tempat Naik', ayahCount: 44, type: 'Makkiyyah', juz: 29 },
  { number: 71, name: 'نوح', englishName: 'Nuh', indonesianName: 'Nuh', ayahCount: 28, type: 'Makkiyyah', juz: 29 },
  { number: 72, name: 'الجن', englishName: 'Al-Jinn', indonesianName: 'Jin', ayahCount: 28, type: 'Makkiyyah', juz: 29 },
  { number: 73, name: 'المزمل', englishName: 'Al-Muzzammil', indonesianName: 'Yang Berselimut', ayahCount: 20, type: 'Makkiyyah', juz: 29 },
  { number: 74, name: 'المدثر', englishName: 'Al-Muddassir', indonesianName: 'Yang Berkemul', ayahCount: 56, type: 'Makkiyyah', juz: 29 },
  { number: 75, name: 'القيامة', englishName: 'Al-Qiyamah', indonesianName: 'Hari Kiamat', ayahCount: 40, type: 'Makkiyyah', juz: 29 },
  { number: 76, name: 'الإنسان', englishName: 'Al-Insan', indonesianName: 'Manusia', ayahCount: 31, type: 'Madaniyyah', juz: 29 },
  { number: 77, name: 'المرسلات', englishName: 'Al-Mursalat', indonesianName: 'Yang Diutus', ayahCount: 50, type: 'Makkiyyah', juz: 29 },
  { number: 78, name: 'النبأ', englishName: 'An-Naba', indonesianName: 'Berita Besar', ayahCount: 40, type: 'Makkiyyah', juz: 30 },
  { number: 79, name: 'النازعات', englishName: 'An-Naziat', indonesianName: 'Yang Mencabut', ayahCount: 46, type: 'Makkiyyah', juz: 30 },
  { number: 80, name: 'عبس', englishName: 'Abasa', indonesianName: 'Ia Berwajah Masam', ayahCount: 42, type: 'Makkiyyah', juz: 30 },
  { number: 81, name: 'التكوير', englishName: 'At-Takwir', indonesianName: 'Penggulung', ayahCount: 29, type: 'Makkiyyah', juz: 30 },
  { number: 82, name: 'الإنفطار', englishName: 'Al-Infitar', indonesianName: 'Terbelah', ayahCount: 19, type: 'Makkiyyah', juz: 30 },
  { number: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', indonesianName: 'Orang yang Curang', ayahCount: 36, type: 'Makkiyyah', juz: 30 },
  { number: 84, name: 'الإنشقاق', englishName: 'Al-Insyiqaq', indonesianName: 'Terbelah', ayahCount: 25, type: 'Makkiyyah', juz: 30 },
  { number: 85, name: 'البروج', englishName: 'Al-Buruj', indonesianName: 'Gugusan Bintang', ayahCount: 22, type: 'Makkiyyah', juz: 30 },
  { number: 86, name: 'الطارق', englishName: 'At-Tariq', indonesianName: 'Yang Datang di Malam Hari', ayahCount: 17, type: 'Makkiyyah', juz: 30 },
  { number: 87, name: 'الأعلى', englishName: 'Al-Ala', indonesianName: 'Yang Paling Tinggi', ayahCount: 19, type: 'Makkiyyah', juz: 30 },
  { number: 88, name: 'الغاشية', englishName: 'Al-Ghasyiyah', indonesianName: 'Hari Pembalasan', ayahCount: 26, type: 'Makkiyyah', juz: 30 },
  { number: 89, name: 'الفجر', englishName: 'Al-Fajr', indonesianName: 'Fajar', ayahCount: 30, type: 'Makkiyyah', juz: 30 },
  { number: 90, name: 'البلد', englishName: 'Al-Balad', indonesianName: 'Negeri', ayahCount: 20, type: 'Makkiyyah', juz: 30 },
  { number: 91, name: 'الشمس', englishName: 'Asy-Syams', indonesianName: 'Matahari', ayahCount: 15, type: 'Makkiyyah', juz: 30 },
  { number: 92, name: 'الليل', englishName: 'Al-Lail', indonesianName: 'Malam', ayahCount: 21, type: 'Makkiyyah', juz: 30 },
  { number: 93, name: 'الضحى', englishName: 'Ad-Duha', indonesianName: 'Waktu Dhuha', ayahCount: 11, type: 'Makkiyyah', juz: 30 },
  { number: 94, name: 'الشرح', englishName: 'Al-Insyirah', indonesianName: 'Kelapangan', ayahCount: 8, type: 'Makkiyyah', juz: 30 },
  { number: 95, name: 'التين', englishName: 'At-Tin', indonesianName: 'Buah Tin', ayahCount: 8, type: 'Makkiyyah', juz: 30 },
  { number: 96, name: 'العلق', englishName: 'Al-Alaq', indonesianName: 'Segumpal Darah', ayahCount: 19, type: 'Makkiyyah', juz: 30 },
  { number: 97, name: 'القدر', englishName: 'Al-Qadr', indonesianName: 'Kemuliaan', ayahCount: 5, type: 'Makkiyyah', juz: 30 },
  { number: 98, name: 'البينة', englishName: 'Al-Bayyinah', indonesianName: 'Bukti yang Nyata', ayahCount: 8, type: 'Madaniyyah', juz: 30 },
  { number: 99, name: 'الزلزلة', englishName: 'Az-Zalzalah', indonesianName: 'Kegoncangan', ayahCount: 8, type: 'Madaniyyah', juz: 30 },
  { number: 100, name: 'العاديات', englishName: 'Al-Adiyat', indonesianName: 'Kuda yang Berlari Kencang', ayahCount: 11, type: 'Makkiyyah', juz: 30 },
  { number: 101, name: 'القارعة', englishName: 'Al-Qariah', indonesianName: 'Hari Kiamat', ayahCount: 11, type: 'Makkiyyah', juz: 30 },
  { number: 102, name: 'التكاثر', englishName: 'At-Takasur', indonesianName: 'Bermegah-megahan', ayahCount: 8, type: 'Makkiyyah', juz: 30 },
  { number: 103, name: 'العصر', englishName: 'Al-Asr', indonesianName: 'Masa', ayahCount: 3, type: 'Makkiyyah', juz: 30 },
  { number: 104, name: 'الهمزة', englishName: 'Al-Humazah', indonesianName: 'Pengumpat', ayahCount: 9, type: 'Makkiyyah', juz: 30 },
  { number: 105, name: 'الفيل', englishName: 'Al-Fil', indonesianName: 'Gajah', ayahCount: 5, type: 'Makkiyyah', juz: 30 },
  { number: 106, name: 'قريش', englishName: 'Quraisy', indonesianName: 'Suku Quraisy', ayahCount: 4, type: 'Makkiyyah', juz: 30 },
  { number: 107, name: 'الماعون', englishName: 'Al-Maun', indonesianName: 'Barang yang Berguna', ayahCount: 7, type: 'Makkiyyah', juz: 30 },
  { number: 108, name: 'الكوثر', englishName: 'Al-Kausar', indonesianName: 'Nikmat yang Banyak', ayahCount: 3, type: 'Makkiyyah', juz: 30 },
  { number: 109, name: 'الكافرون', englishName: 'Al-Kafirun', indonesianName: 'Orang-orang Kafir', ayahCount: 6, type: 'Makkiyyah', juz: 30 },
  { number: 110, name: 'النصر', englishName: 'An-Nasr', indonesianName: 'Pertolongan', ayahCount: 3, type: 'Madaniyyah', juz: 30 },
  { number: 111, name: 'المسد', englishName: 'Al-Masad', indonesianName: 'Sabut', ayahCount: 5, type: 'Makkiyyah', juz: 30 },
  { number: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', indonesianName: 'Ikhlas', ayahCount: 4, type: 'Makkiyyah', juz: 30 },
  { number: 113, name: 'الفلق', englishName: 'Al-Falaq', indonesianName: 'Waktu Subuh', ayahCount: 5, type: 'Makkiyyah', juz: 30 },
  { number: 114, name: 'الناس', englishName: 'An-Nas', indonesianName: 'Manusia', ayahCount: 6, type: 'Makkiyyah', juz: 30 },
];
